### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by mmaedel** [jeggett/call-adviser#1]
mädel@schnee /cygdrive/c/Users/mädel/documents/github/call-adviser
$ npm start

> react-boilerplate@3.0.0 start C:\Users\mädel\documents\github\call-adviser
> npm run start:tunnel
> 
> react-boilerplate@3.0.0 start:tunnel C:\Users\mädel\documents\github\call-adviser
> cross-env NODE_ENV=development node server

Server started ✓
Tunnel initialised ✓
## Access URLs:

Localhost: http://localhost:3000
      LAN: http://192.168.56.1:3000
##     Proxy: https://b9d364f4.ngrok.io

Press CTRL-C to stop

webpack built f409b776f8494d2f570f in 22241ms

WARNING in ./~/react/react.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\react.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\redbox-react\lib\index.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\react.js
  Used by 52 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\babel-loader\index.js?{"presets":["react-hmre"]}!C:\Users\mädel\documents\github\call-adviser\app\app.js

WARNING in ./~/react/lib/React.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\react.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\react.js

WARNING in ./~/react/lib/ReactChildren.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactChildren.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactChildren.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactClass.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactClass.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactComponent.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponent.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactComponent.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactDOMFactories.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDOMFactories.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDOMFactories.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactElement.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactElement.js
  Used by 8 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactElement.js
  Used by 11 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactElementValidator.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactElementValidator.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactElementValidator.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactPropTypes.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactPropTypes.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactPropTypes.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/ReactVersion.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactVersion.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactVersion.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/react/lib/onlyChild.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\onlyChild.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\onlyChild.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/object-assign/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\object-assign\index.js
  Used by 4 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\redbox-react\lib\index.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\object-assign\index.js
  Used by 23 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/fbjs/lib/warning.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\warning.js
  Used by 9 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\React.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\warning.js
  Used by 32 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\React.js

WARNING in ./~/fbjs/lib/ExecutionEnvironment.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\ExecutionEnvironment.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDebugTool.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\ExecutionEnvironment.js
  Used by 17 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDOM.js

WARNING in ./~/react/lib/PooledClass.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\PooledClass.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactChildren.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\PooledClass.js
  Used by 8 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactChildren.js

WARNING in ./~/fbjs/lib/emptyFunction.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\emptyFunction.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactChildren.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\emptyFunction.js
  Used by 12 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactChildren.js

WARNING in ./~/react/lib/traverseAllChildren.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\traverseAllChildren.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactChildren.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\traverseAllChildren.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactChildren.js

WARNING in ./~/fbjs/lib/mapObject.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\mapObject.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDOMFactories.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\mapObject.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDOMFactories.js

WARNING in ./~/react/lib/ReactPropTypeLocations.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactPropTypeLocations.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactClass.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactPropTypeLocations.js
  Used by 4 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/react/lib/ReactPropTypeLocationNames.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactPropTypeLocationNames.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactClass.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactPropTypeLocationNames.js
  Used by 4 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/react/lib/ReactNoopUpdateQueue.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactNoopUpdateQueue.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponent.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactNoopUpdateQueue.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/fbjs/lib/emptyObject.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\emptyObject.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponent.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\emptyObject.js
  Used by 4 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/fbjs/lib/invariant.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\invariant.js
  Used by 8 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponent.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\invariant.js
  Used by 39 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/fbjs/lib/keyMirror.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\keyMirror.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactClass.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\keyMirror.js
  Used by 4 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/fbjs/lib/keyOf.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\keyOf.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactClass.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\keyOf.js
  Used by 8 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactClass.js

WARNING in ./~/react/lib/ReactCurrentOwner.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactCurrentOwner.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactElement.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactCurrentOwner.js
  Used by 8 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactElement.js

WARNING in ./~/react/lib/canDefineProperty.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\canDefineProperty.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponent.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\canDefineProperty.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactElement.js

WARNING in ./~/react/lib/getIteratorFn.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\getIteratorFn.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactElementValidator.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\getIteratorFn.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactElementValidator.js

WARNING in ./~/react/lib/ReactInstrumentation.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactInstrumentation.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponent.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactInstrumentation.js
  Used by 12 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactComponent.js

WARNING in ./~/lodash/_getPrototype.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\lodash_getPrototype.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\lodash_baseHas.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\lodash_getPrototype.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\lodash\isPlainObject.js

WARNING in ./~/lodash/_isHostObject.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\lodash_isHostObject.js
  Used by 2 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\lodash_baseIsEqualDeep.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\lodash_isHostObject.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\lodash\isPlainObject.js

WARNING in ./~/lodash/isObjectLike.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\lodash\isObjectLike.js
  Used by 5 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\lodash\isArrayLikeObject.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\lodash\isObjectLike.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\lodash\isPlainObject.js

WARNING in ./~/react/lib/KeyEscapeUtils.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\KeyEscapeUtils.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\traverseAllChildren.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\KeyEscapeUtils.js
  Used by 3 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\traverseAllChildren.js

WARNING in ./~/react/lib/ReactDebugTool.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDebugTool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactInstrumentation.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDebugTool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactInstrumentation.js

WARNING in ./~/fbjs/lib/performanceNow.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\performanceNow.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDebugTool.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\performanceNow.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDebugTool.js

WARNING in ./~/react/lib/ReactInvalidSetStateWarningDevTool.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactInvalidSetStateWarningDevTool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDebugTool.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactInvalidSetStateWarningDevTool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDebugTool.js

WARNING in ./~/react/lib/ReactNativeOperationHistoryDevtool.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactNativeOperationHistoryDevtool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDebugTool.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactNativeOperationHistoryDevtool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDebugTool.js

WARNING in ./~/react/lib/ReactComponentTreeDevtool.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactComponentTreeDevtool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\react\lib\ReactDebugTool.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactComponentTreeDevtool.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\react\lib\ReactDebugTool.js

WARNING in ./~/fbjs/lib/performance.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\performance.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\Documents\GitHub\call-adviser\node_modules\fbjs\lib\performanceNow.js
- C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\performance.js
  Used by 1 module(s), i. e.
  C:\Users\mädel\documents\github\call-adviser\node_modules\fbjs\lib\performanceNow.js
  Child html-webpack-plugin for "index.html":

dule(s), i. e

**Comment by jeggett** [comment]
looks like these are warnings not errors

**Comment by tamj0rd2** [comment]
@jeggett But how can they be fixed? I don't have any modules with the same names as far as I can see...

**Comment by jeggett** [comment]
@tamj0rd2 How did you stumbled upon this project? =)  What modules do you mean? It should be some Windows specific issue, probably...

**Comment by tamj0rd2** [comment]
@jeggett Ignore me, sorry for my comment. I came across this from Google and thought this issue was in a different repo!
